version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6.8
        working_directory: ~/blog
#        environment:
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                    - "ae:b2:cc:f6:26:21:35:d6:9d:2e:03:cd:ed:a3:5c:3d"
            - run: |
                ./setup.sh
                ./run.sh
            - deploy:
                name: Deploy
                command: |
                    git config --global user.email $GH_EMAIL
                    git config --global user.name $GH_NAME
                    git clone git@github.com:dsschult/dsschult.github.io.git
                    rsync -ai --delete --exclude CNAME --exclude .git build/ dsschult.github.io/
                    cd dsschult.github.io
                    git add -A
                    git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
                    git push
workflows:
    version: 2
    build_and_test:
        jobs:
            - build