version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6.8
        working_directory: ~/blog
#        environment:
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                    - "cb:0d:69:a9:13:90:a6:a7:d1:ee:e0:b6:81:c6:0e:74"
            - run: |
                ./setup.sh
                ./run.sh
            - deploy:
                name: Deploy
                command: |
                    git config --global user.email $GH_EMAIL
                    git config --global user.name $GH_NAME
                    git clone git@github.com:dsschult/dsschult.github.io.git
                    cp dsschult.github.io/CNAME build/CNAME
                    cd dsschult.github.io
                    git rm -rf *
                    cp -a ../build/. .
                    git add -A
                    git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
                    git push
workflows:
    version: 2
    build_and_test:
        jobs:
            - build